"""add media items and links

Revision ID: 95a38ae1f9a2
Revises: d3a9c5e75a4c
Create Date: 2026-05-04 21:08:39.974606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a38ae1f9a2'
down_revision: Union[str, Sequence[str], None] = 'd3a9c5e75a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_title'), 'media_items', ['title'], unique=False)
    op.create_index(op.f('ix_media_items_type'), 'media_items', ['type'], unique=False)
    op.create_index(op.f('ix_media_items_user_id'), 'media_items', ['user_id'], unique=False)
    op.create_table('media_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_media_id', sa.UUID(), nullable=False),
    sa.Column('target_media_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_media_id <> target_media_id', name='ck_media_links_not_self'),
    sa.ForeignKeyConstraint(['source_media_id'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['target_media_id'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_media_id', 'target_media_id', 'relation_type', name='uq_media_links_source_target_relation')
    )
    op.create_index(op.f('ix_media_links_relation_type'), 'media_links', ['relation_type'], unique=False)
    op.create_index(op.f('ix_media_links_source_media_id'), 'media_links', ['source_media_id'], unique=False)
    op.create_index(op.f('ix_media_links_target_media_id'), 'media_links', ['target_media_id'], unique=False)
    op.create_index(op.f('ix_media_links_user_id'), 'media_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_links_user_id'), table_name='media_links')
    op.drop_index(op.f('ix_media_links_target_media_id'), table_name='media_links')
    op.drop_index(op.f('ix_media_links_source_media_id'), table_name='media_links')
    op.drop_index(op.f('ix_media_links_relation_type'), table_name='media_links')
    op.drop_table('media_links')
    op.drop_index(op.f('ix_media_items_user_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_type'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_title'), table_name='media_items')
    op.drop_table('media_items')
    # ### end Alembic commands ###
